spring.application.name=thiep
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/thiep_db?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Ho_Chi_Minh
spring.datasource.username=thiep_user
spring.datasource.password=thiep123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# admin seed (t? t?o admin khi ch?y)
app.admin.email=admin@thiep.local
app.admin.password=admin123456
